### ISSUE TITLE
During testing, the results are not controlled by input image but affected by the Ground-Truth (GT) Point Cloud

### ISSUE THREAD

**Issue by weiyao1996** [pittcps/sat2pc#1]
Dear authors,

Many thanks for your great work and open source code! 
When I tried to train and test your model on my own dataset, I observe that the generated results look amazing, i.e., very close to GTs. I would say, most of the results seem exactly the same as their GTs, so I tried to replace real GTs by fake GTs during testing and then, I notice that the results and (fake) GTs are still very similar.
I wonder if there is something wrong for your data loader please? Looking forward for your help.

Regards,
Yao

**Comment by stephenlee86** [comment]
Yao, Thanks for reaching out. Can you provide a data sample? I can test it out locally
